modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MightyPirates/Scannable/issues"

[[mods]]
    modId="scannable"
    version="${version}"
    displayName="Scannable"
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional TODO
# A URL for the "homepage" for this mod, displayed in the mod UI
    displayURL="https://github.com/MightyPirates/Scannable"
    authors="Sangar"
    description="Scan the area for points of interest."
[[dependencies.scannable]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.scannable]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"